name: Build and publish Docker image to GHCR

on:
  push:
    tags:
      - '*'     # Triggers whenever a new tag is pushed. Adjust the pattern as needed.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read        # Allows reading the repository contents
      packages: write       # Allows pushing packages (Docker images) to GHCR

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile              # Path to your Dockerfile
          push: true                      # Push the image after building
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
